spring:
  datasource:
    url: jdbc:mysql://team4-dev.cdyqug0y0dy3.ap-northeast-2.rds.amazonaws.com:3306/team4DB
    username: root
    password: team4database
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  swagger-ui:
    path: api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**
  use-fqn: true
cloud:
  aws:
    s3:
      bucket: umc-team4-bucket
      path:
        image: image
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}